# Generated by Django 5.0.6 on 2024-06-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="saved_image_urls",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="saved_photos_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
